// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/ashwinyue/eino-show/internal/apiserver/biz"
	"github.com/ashwinyue/eino-show/internal/apiserver/cache"
	"github.com/ashwinyue/eino-show/internal/apiserver/pkg/validation"
	"github.com/ashwinyue/eino-show/internal/apiserver/store"
	"github.com/ashwinyue/eino-show/internal/pkg/server"
)

// Injectors from wire.go:

func InitializeWebServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	client, err := ProvideRedisOrNone(config)
	if err != nil {
		return nil, err
	}
	_ = cache.NewRedisCache(client) // 缓存实例，后续可注入到需要的地方
	datastore := store.NewStore(db)
	iBiz := biz.NewBiz(datastore, client) // 传入 Redis client 用于 LLM Context 存储
	validator := validation.New(datastore)
	userRetriever := &UserRetriever{
		store: datastore,
	}
	serverConfig := &ServerConfig{
		cfg:       config,
		biz:       iBiz,
		val:       validator,
		retriever: userRetriever,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
