// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthTokenM = "auth_tokens"

// AuthTokenM mapped from table <auth_tokens>
type AuthTokenM struct {
	ID        string     `gorm:"column:id;primaryKey;default:uuid_generate_v4();comment:Unique identifier of the token" json:"id"` // Unique identifier of the token
	UserID    string     `gorm:"column:user_id;not null;comment:User ID that owns this token" json:"user_id"`                      // User ID that owns this token
	Token     string     `gorm:"column:token;not null;comment:Token value (JWT or other format)" json:"token"`                     // Token value (JWT or other format)
	TokenType string     `gorm:"column:token_type;not null;comment:Token type (access_token, refresh_token)" json:"token_type"`    // Token type (access_token, refresh_token)
	ExpiresAt time.Time  `gorm:"column:expires_at;not null;comment:Token expiration time" json:"expires_at"`                       // Token expiration time
	IsRevoked bool       `gorm:"column:is_revoked;not null;comment:Whether the token is revoked" json:"is_revoked"`                // Whether the token is revoked
	CreatedAt *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName AuthTokenM's table name
func (*AuthTokenM) TableName() string {
	return TableNameAuthTokenM
}
