// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameChunkM = "chunks"

// ChunkM mapped from table <chunks>
type ChunkM struct {
	ID                     string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	TenantID               int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	KnowledgeBaseID        string         `gorm:"column:knowledge_base_id;not null" json:"knowledge_base_id"`
	KnowledgeID            string         `gorm:"column:knowledge_id;not null" json:"knowledge_id"`
	Content                string         `gorm:"column:content;not null" json:"content"`
	ChunkIndex             int32          `gorm:"column:chunk_index;not null" json:"chunk_index"`
	IsEnabled              bool           `gorm:"column:is_enabled;not null;default:true" json:"is_enabled"`
	StartAt                int32          `gorm:"column:start_at;not null" json:"start_at"`
	EndAt                  int32          `gorm:"column:end_at;not null" json:"end_at"`
	PreChunkID             *string        `gorm:"column:pre_chunk_id" json:"pre_chunk_id"`
	NextChunkID            *string        `gorm:"column:next_chunk_id" json:"next_chunk_id"`
	ChunkType              string         `gorm:"column:chunk_type;not null;default:text" json:"chunk_type"`
	ParentChunkID          *string        `gorm:"column:parent_chunk_id" json:"parent_chunk_id"`
	ImageInfo              *string        `gorm:"column:image_info" json:"image_info"`
	RelationChunks         *string        `gorm:"column:relation_chunks" json:"relation_chunks"`
	IndirectRelationChunks *string        `gorm:"column:indirect_relation_chunks" json:"indirect_relation_chunks"`
	CreatedAt              *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt              *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt              gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Metadata               *string        `gorm:"column:metadata" json:"metadata"`
	TagID                  *string        `gorm:"column:tag_id" json:"tag_id"`
	Status                 int32          `gorm:"column:status;not null" json:"status"`
	ContentHash            *string        `gorm:"column:content_hash" json:"content_hash"`
	Flags                  int32          `gorm:"column:flags;not null;default:1" json:"flags"`
}

// TableName ChunkM's table name
func (*ChunkM) TableName() string {
	return TableNameChunkM
}
