// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCustomAgentM = "custom_agents"

// CustomAgentM mapped from table <custom_agents>
type CustomAgentM struct {
	ID          string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description *string        `gorm:"column:description" json:"description"`
	Avatar      *string        `gorm:"column:avatar" json:"avatar"`
	IsBuiltin   bool           `gorm:"column:is_builtin;not null" json:"is_builtin"`
	TenantID    int32          `gorm:"column:tenant_id;primaryKey" json:"tenant_id"`
	CreatedBy   *string        `gorm:"column:created_by" json:"created_by"`
	Config      string         `gorm:"column:config;not null;default:{}" json:"config"`
	CreatedAt   *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CustomAgentM's table name
func (*CustomAgentM) TableName() string {
	return TableNameCustomAgentM
}
