// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmbeddingM = "embeddings"

// EmbeddingM mapped from table <embeddings>
type EmbeddingM struct {
	ID              int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt       *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	SourceID        string     `gorm:"column:source_id;not null" json:"source_id"`
	SourceType      int32      `gorm:"column:source_type;not null" json:"source_type"`
	ChunkID         *string    `gorm:"column:chunk_id" json:"chunk_id"`
	KnowledgeID     *string    `gorm:"column:knowledge_id" json:"knowledge_id"`
	KnowledgeBaseID *string    `gorm:"column:knowledge_base_id" json:"knowledge_base_id"`
	TagID           *string    `gorm:"column:tag_id" json:"tag_id"`
	Content         *string    `gorm:"column:content" json:"content"`
	Dimension       int32      `gorm:"column:dimension;not null" json:"dimension"`
	Embedding       *string    `gorm:"column:embedding" json:"embedding"`
}

// TableName EmbeddingM's table name
func (*EmbeddingM) TableName() string {
	return TableNameEmbeddingM
}
