// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameKnowledgeTagM = "knowledge_tags"

// KnowledgeTagM mapped from table <knowledge_tags>
type KnowledgeTagM struct {
	ID              string         `gorm:"column:id;primaryKey" json:"id"`
	TenantID        int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	KnowledgeBaseID string         `gorm:"column:knowledge_base_id;not null" json:"knowledge_base_id"`
	Name            string         `gorm:"column:name;not null" json:"name"`
	Color           *string        `gorm:"column:color" json:"color"`
	SortOrder       int32          `gorm:"column:sort_order;not null" json:"sort_order"`
	CreatedAt       *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName KnowledgeTagM's table name
func (*KnowledgeTagM) TableName() string {
	return TableNameKnowledgeTagM
}
