// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameKnowledgeBaseM = "knowledge_bases"

// KnowledgeBaseM mapped from table <knowledge_bases>
type KnowledgeBaseM struct {
	ID                       string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name                     string         `gorm:"column:name;not null" json:"name"`
	Description              *string        `gorm:"column:description" json:"description"`
	TenantID                 int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	ChunkingConfig           string         `gorm:"column:chunking_config;not null;default:{" json:"chunking_config"`
	ImageProcessingConfig    string         `gorm:"column:image_processing_config;not null;default:{" json:"image_processing_config"`
	EmbeddingModelID         string         `gorm:"column:embedding_model_id;not null" json:"embedding_model_id"`
	SummaryModelID           string         `gorm:"column:summary_model_id;not null" json:"summary_model_id"`
	CosConfig                string         `gorm:"column:cos_config;not null;default:{}" json:"cos_config"`
	VlmConfig                string         `gorm:"column:vlm_config;not null;default:{}" json:"vlm_config"`
	ExtractConfig            *string        `gorm:"column:extract_config" json:"extract_config"`
	CreatedAt                *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt                *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt                gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	IsTemporary              bool           `gorm:"column:is_temporary;not null;comment:Whether this knowledge base is temporary (ephemeral) and should be hidden from UI" json:"is_temporary"` // Whether this knowledge base is temporary (ephemeral) and should be hidden from UI
	Type                     string         `gorm:"column:type;not null;default:document" json:"type"`
	FaqConfig                *string        `gorm:"column:faq_config" json:"faq_config"`
	QuestionGenerationConfig *string        `gorm:"column:question_generation_config" json:"question_generation_config"`
}

// TableName KnowledgeBaseM's table name
func (*KnowledgeBaseM) TableName() string {
	return TableNameKnowledgeBaseM
}
