// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameKnowledgeM = "knowledges"

// KnowledgeM mapped from table <knowledges>
type KnowledgeM struct {
	ID               string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	TenantID         int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	KnowledgeBaseID  string         `gorm:"column:knowledge_base_id;not null" json:"knowledge_base_id"`
	Type             string         `gorm:"column:type;not null" json:"type"`
	Title            string         `gorm:"column:title;not null" json:"title"`
	Description      *string        `gorm:"column:description" json:"description"`
	Source           string         `gorm:"column:source;not null" json:"source"`
	ParseStatus      string         `gorm:"column:parse_status;not null;default:unprocessed" json:"parse_status"`
	EnableStatus     string         `gorm:"column:enable_status;not null;default:enabled" json:"enable_status"`
	EmbeddingModelID *string        `gorm:"column:embedding_model_id" json:"embedding_model_id"`
	FileName         *string        `gorm:"column:file_name" json:"file_name"`
	FileType         *string        `gorm:"column:file_type" json:"file_type"`
	FileSize         *int64         `gorm:"column:file_size" json:"file_size"`
	FilePath         *string        `gorm:"column:file_path" json:"file_path"`
	FileHash         *string        `gorm:"column:file_hash" json:"file_hash"`
	StorageSize      int64          `gorm:"column:storage_size;not null" json:"storage_size"`
	Metadata         *string        `gorm:"column:metadata" json:"metadata"`
	CreatedAt        *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	ProcessedAt      *time.Time     `gorm:"column:processed_at" json:"processed_at"`
	ErrorMessage     *string        `gorm:"column:error_message" json:"error_message"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	TagID            *string        `gorm:"column:tag_id" json:"tag_id"`
	SummaryStatus    *string        `gorm:"column:summary_status;default:none" json:"summary_status"`
}

// TableName KnowledgeM's table name
func (*KnowledgeM) TableName() string {
	return TableNameKnowledgeM
}
