// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMCPServiceM = "mcp_services"

// MCPServiceM mapped from table <mcp_services>
type MCPServiceM struct {
	ID             string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	TenantID       int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Name           string         `gorm:"column:name;not null" json:"name"`
	Description    *string        `gorm:"column:description" json:"description"`
	Enabled        *bool          `gorm:"column:enabled;default:true" json:"enabled"`
	TransportType  string         `gorm:"column:transport_type;not null" json:"transport_type"`
	URL            *string        `gorm:"column:url" json:"url"`
	Headers        *string        `gorm:"column:headers" json:"headers"`
	AuthConfig     *string        `gorm:"column:auth_config" json:"auth_config"`
	AdvancedConfig *string        `gorm:"column:advanced_config" json:"advanced_config"`
	StdioConfig    *string        `gorm:"column:stdio_config" json:"stdio_config"`
	EnvVars        *string        `gorm:"column:env_vars" json:"env_vars"`
	CreatedAt      *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName MCPServiceM's table name
func (*MCPServiceM) TableName() string {
	return TableNameMCPServiceM
}
