// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessageM = "messages"

// MessageM mapped from table <messages>
type MessageM struct {
	ID                  string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	RequestID           string         `gorm:"column:request_id;not null" json:"request_id"`
	SessionID           string         `gorm:"column:session_id;not null" json:"session_id"`
	Role                string         `gorm:"column:role;not null" json:"role"`
	Content             string         `gorm:"column:content;not null" json:"content"`
	KnowledgeReferences string         `gorm:"column:knowledge_references;not null;default:[]" json:"knowledge_references"`
	AgentSteps          *string        `gorm:"column:agent_steps;comment:Agent execution steps (reasoning process and tool calls)" json:"agent_steps"` // Agent execution steps (reasoning process and tool calls)
	IsCompleted         bool           `gorm:"column:is_completed;not null" json:"is_completed"`
	CreatedAt           *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt           *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	MentionedItems      *string        `gorm:"column:mentioned_items;default:[];comment:Stores @mentioned knowledge bases and files (id, name, type) when user sends a message" json:"mentioned_items"` // Stores @mentioned knowledge bases and files (id, name, type) when user sends a message
}

// TableName MessageM's table name
func (*MessageM) TableName() string {
	return TableNameMessageM
}
