// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSessionM = "sessions"

// SessionM mapped from table <sessions>
type SessionM struct {
	ID                string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	TenantID          int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Title             *string        `gorm:"column:title" json:"title"`
	Description       *string        `gorm:"column:description" json:"description"`
	KnowledgeBaseID   *string        `gorm:"column:knowledge_base_id" json:"knowledge_base_id"`
	MaxRounds         int32          `gorm:"column:max_rounds;not null;default:5" json:"max_rounds"`
	EnableRewrite     bool           `gorm:"column:enable_rewrite;not null;default:true" json:"enable_rewrite"`
	FallbackStrategy  string         `gorm:"column:fallback_strategy;not null;default:fixed" json:"fallback_strategy"`
	FallbackResponse  string         `gorm:"column:fallback_response;not null;default:很抱歉，我暂时无法回答这个问题。" json:"fallback_response"`
	KeywordThreshold  float64        `gorm:"column:keyword_threshold;not null;default:0.5" json:"keyword_threshold"`
	VectorThreshold   float64        `gorm:"column:vector_threshold;not null;default:0.5" json:"vector_threshold"`
	RerankModelID     *string        `gorm:"column:rerank_model_id" json:"rerank_model_id"`
	EmbeddingTopK     int32          `gorm:"column:embedding_top_k;not null;default:10" json:"embedding_top_k"`
	RerankTopK        int32          `gorm:"column:rerank_top_k;not null;default:10" json:"rerank_top_k"`
	RerankThreshold   float64        `gorm:"column:rerank_threshold;not null;default:0.65" json:"rerank_threshold"`
	SummaryModelID    *string        `gorm:"column:summary_model_id" json:"summary_model_id"`
	SummaryParameters string         `gorm:"column:summary_parameters;not null;default:{}" json:"summary_parameters"`
	AgentConfig       *string        `gorm:"column:agent_config;comment:Session-level agent configuration in JSON format" json:"agent_config"`                         // Session-level agent configuration in JSON format
	ContextConfig     *string        `gorm:"column:context_config;comment:LLM context management configuration (separate from message storage)" json:"context_config"` // LLM context management configuration (separate from message storage)
	CreatedAt         *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	AgentID           *string        `gorm:"column:agent_id" json:"agent_id"`
}

// TableName SessionM's table name
func (*SessionM) TableName() string {
	return TableNameSessionM
}
