// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTenantM = "tenants"

// TenantM mapped from table <tenants>
type TenantM struct {
	ID                 int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name               string         `gorm:"column:name;not null" json:"name"`
	Description        *string        `gorm:"column:description" json:"description"`
	APIKey             string         `gorm:"column:api_key;not null;default:(gen_random_uuid())" json:"api_key"`
	RetrieverEngines   string         `gorm:"column:retriever_engines;not null;default:[]" json:"retriever_engines"`
	Status             *string        `gorm:"column:status;default:active" json:"status"`
	Business           string         `gorm:"column:business;not null" json:"business"`
	StorageQuota       int64          `gorm:"column:storage_quota;not null;default:10737418240" json:"storage_quota"`
	StorageUsed        int64          `gorm:"column:storage_used;not null" json:"storage_used"`
	AgentConfig        *string        `gorm:"column:agent_config" json:"agent_config"`
	CreatedAt          *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	ContextConfig      *string        `gorm:"column:context_config" json:"context_config"`
	ConversationConfig *string        `gorm:"column:conversation_config" json:"conversation_config"`
	WebSearchConfig    *string        `gorm:"column:web_search_config" json:"web_search_config"`
}

// TableName TenantM's table name
func (*TenantM) TableName() string {
	return TableNameTenantM
}
