// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserM = "users"

// UserM mapped from table <users>
type UserM struct {
	ID                  string         `gorm:"column:id;primaryKey;default:uuid_generate_v4();comment:Unique identifier of the user" json:"id"` // Unique identifier of the user
	Username            string         `gorm:"column:username;not null;comment:Username of the user" json:"username"`                           // Username of the user
	Email               string         `gorm:"column:email;not null;comment:Email address of the user" json:"email"`                            // Email address of the user
	PasswordHash        string         `gorm:"column:password_hash;not null;comment:Hashed password of the user" json:"password_hash"`          // Hashed password of the user
	Avatar              *string        `gorm:"column:avatar;comment:Avatar URL of the user" json:"avatar"`                                      // Avatar URL of the user
	TenantID            *int32         `gorm:"column:tenant_id;comment:Tenant ID that the user belongs to" json:"tenant_id"`                    // Tenant ID that the user belongs to
	IsActive            bool           `gorm:"column:is_active;not null;default:true;comment:Whether the user is active" json:"is_active"`      // Whether the user is active
	CreatedAt           *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt           *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CanAccessAllTenants bool           `gorm:"column:can_access_all_tenants;not null" json:"can_access_all_tenants"`
}

// TableName UserM's table name
func (*UserM) TableName() string {
	return TableNameUserM
}
