// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWorkflowCheckpointM = "workflow_checkpoints"

// WorkflowCheckpointM mapped from table <workflow_checkpoints>
type WorkflowCheckpointM struct {
	ID            string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	SessionID     string         `gorm:"column:session_id;not null;comment:关联的会话 ID" json:"session_id"` // 关联的会话 ID
	AgentID       string         `gorm:"column:agent_id;not null;comment:关联的 Agent ID" json:"agent_id"` // 关联的 Agent ID
	TenantID      int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	WorkflowState string         `gorm:"column:workflow_state;not null;default:{};comment:Workflow 执行状态 (JSON)" json:"workflow_state"` // Workflow 执行状态 (JSON)
	InterruptInfo *string        `gorm:"column:interrupt_info;comment:中断信息 (JSON)" json:"interrupt_info"`                              // 中断信息 (JSON)
	Status        string         `gorm:"column:status;not null;default:pending;comment:状态: pending, completed, failed" json:"status"`  // 状态: pending, completed, failed
	CreatedAt     *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName WorkflowCheckpointM's table name
func (*WorkflowCheckpointM) TableName() string {
	return TableNameWorkflowCheckpointM
}
