// Copyright 2026 阿斯温月 <stary99c@163.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/ashwinyue/eino-show. The professional
// version of this repository is https://github.com/onexstack/onex.

// eino-show API 定义，包含健康检查、用户管理、文章管理、Agent管理、会话管理和知识库管理的 RPC 接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apiserver/v1/apiserver.proto

package apiserverv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apiserver_v1_apiserver_proto protoreflect.FileDescriptor

const file_apiserver_v1_apiserver_proto_rawDesc = "" +
	"\n" +
	"\x1capiserver/v1/apiserver.proto\x12\fapiserver.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1aapiserver/v1/healthz.proto\x1a\x17apiserver/v1/post.proto\x1a\x17apiserver/v1/user.proto\x1a\x18apiserver/v1/agent.proto\x1a\x1aapiserver/v1/session.proto\x1a\x1capiserver/v1/knowledge.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe7*\n" +
	"\bMiniBlog\x12\x80\x01\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x1d.apiserver.v1.HealthzResponse\">\x92A+\n" +
	"\f服务治理\x12\x12服务健康检查*\aHealthz\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12y\n" +
	"\x05Login\x12\x1a.apiserver.v1.LoginRequest\x1a\x1b.apiserver.v1.LoginResponse\"7\x92A#\n" +
	"\f用户管理\x12\f用户登录*\x05Login\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/login\x12\x9d\x01\n" +
	"\fRefreshToken\x12!.apiserver.v1.RefreshTokenRequest\x1a\".apiserver.v1.RefreshTokenResponse\"F\x92A*\n" +
	"\f用户管理\x12\f刷新令牌*\fRefreshToken\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/refresh-token\x12\xb9\x01\n" +
	"\x0eChangePassword\x12#.apiserver.v1.ChangePasswordRequest\x1a$.apiserver.v1.ChangePasswordResponse\"\\\x92A,\n" +
	"\f用户管理\x12\f修改密码*\x0eChangePassword\x82\xd3\xe4\x93\x02':\x01*\x1a\"/v1/users/{userID}/change-password\x12\x90\x01\n" +
	"\n" +
	"CreateUser\x12\x1f.apiserver.v1.CreateUserRequest\x1a .apiserver.v1.CreateUserResponse\"?\x92A(\n" +
	"\f用户管理\x12\f创建用户*\n" +
	"CreateUser\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12\x9f\x01\n" +
	"\n" +
	"UpdateUser\x12\x1f.apiserver.v1.UpdateUserRequest\x1a .apiserver.v1.UpdateUserResponse\"N\x92A.\n" +
	"\f用户管理\x12\x12更新用户信息*\n" +
	"UpdateUser\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/users/{userID}\x12\x96\x01\n" +
	"\n" +
	"DeleteUser\x12\x1f.apiserver.v1.DeleteUserRequest\x1a .apiserver.v1.DeleteUserResponse\"E\x92A(\n" +
	"\f用户管理\x12\f删除用户*\n" +
	"DeleteUser\x82\xd3\xe4\x93\x02\x14*\x12/v1/users/{userID}\x12\x90\x01\n" +
	"\aGetUser\x12\x1c.apiserver.v1.GetUserRequest\x1a\x1d.apiserver.v1.GetUserResponse\"H\x92A+\n" +
	"\f用户管理\x12\x12获取用户信息*\aGetUser\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/users/{userID}\x12\x8b\x01\n" +
	"\bListUser\x12\x1d.apiserver.v1.ListUserRequest\x1a\x1e.apiserver.v1.ListUserResponse\"@\x92A,\n" +
	"\f用户管理\x12\x12列出所有用户*\bListUser\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\x90\x01\n" +
	"\n" +
	"CreatePost\x12\x1f.apiserver.v1.CreatePostRequest\x1a .apiserver.v1.CreatePostResponse\"?\x92A(\n" +
	"\f博客管理\x12\f创建文章*\n" +
	"CreatePost\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/posts\x12\x99\x01\n" +
	"\n" +
	"UpdatePost\x12\x1f.apiserver.v1.UpdatePostRequest\x1a .apiserver.v1.UpdatePostResponse\"H\x92A(\n" +
	"\f博客管理\x12\f更新文章*\n" +
	"UpdatePost\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/posts/{postID}\x12\x90\x01\n" +
	"\n" +
	"DeletePost\x12\x1f.apiserver.v1.DeletePostRequest\x1a .apiserver.v1.DeletePostResponse\"?\x92A(\n" +
	"\f博客管理\x12\f删除文章*\n" +
	"DeletePost\x82\xd3\xe4\x93\x02\x0e:\x01**\t/v1/posts\x12\x90\x01\n" +
	"\aGetPost\x12\x1c.apiserver.v1.GetPostRequest\x1a\x1d.apiserver.v1.GetPostResponse\"H\x92A+\n" +
	"\f博客管理\x12\x12获取文章信息*\aGetPost\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/posts/{postID}\x12\x8b\x01\n" +
	"\bListPost\x12\x1d.apiserver.v1.ListPostRequest\x1a\x1e.apiserver.v1.ListPostResponse\"@\x92A,\n" +
	"\f博客管理\x12\x12列出所有文章*\bListPost\x82\xd3\xe4\x93\x02\v\x12\t/v1/posts\x12\x9c\x01\n" +
	"\n" +
	"ListAgents\x12\x1f.apiserver.v1.ListAgentsRequest\x1a .apiserver.v1.ListAgentsResponse\"K\x92A/\n" +
	"\fAgent 管理\x12\x13获取 Agent 列表*\n" +
	"ListAgents\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/custom-agents\x12\x99\x01\n" +
	"\bGetAgent\x12\x1d.apiserver.v1.GetAgentRequest\x1a\x1e.apiserver.v1.GetAgentResponse\"N\x92A-\n" +
	"\fAgent 管理\x12\x13获取 Agent 详情*\bGetAgent\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/custom-agents/{id}\x12\x9c\x01\n" +
	"\vCreateAgent\x12 .apiserver.v1.CreateAgentRequest\x1a!.apiserver.v1.CreateAgentResponse\"H\x92A)\n" +
	"\fAgent 管理\x12\f创建 Agent*\vCreateAgent\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/custom-agents\x12\xa1\x01\n" +
	"\vUpdateAgent\x12 .apiserver.v1.UpdateAgentRequest\x1a!.apiserver.v1.UpdateAgentResponse\"M\x92A)\n" +
	"\fAgent 管理\x12\f更新 Agent*\vUpdateAgent\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v1/custom-agents/{id}\x12\x9e\x01\n" +
	"\vDeleteAgent\x12 .apiserver.v1.DeleteAgentRequest\x1a!.apiserver.v1.DeleteAgentResponse\"J\x92A)\n" +
	"\fAgent 管理\x12\f删除 Agent*\vDeleteAgent\x82\xd3\xe4\x93\x02\x18*\x16/v1/custom-agents/{id}\x12\xbf\x01\n" +
	"\x11ListBuiltinAgents\x12&.apiserver.v1.ListBuiltinAgentsRequest\x1a'.apiserver.v1.ListBuiltinAgentsResponse\"Y\x92A<\n" +
	"\fAgent 管理\x12\x19获取内置 Agent 列表*\x11ListBuiltinAgents\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/agents/builtin\x12\x9f\x01\n" +
	"\rCreateSession\x12\".apiserver.v1.CreateSessionRequest\x1a#.apiserver.v1.CreateSessionResponse\"E\x92A+\n" +
	"\f会话管理\x12\f创建会话*\rCreateSession\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/sessions\x12\x9b\x01\n" +
	"\n" +
	"GetSession\x12\x1f.apiserver.v1.GetSessionRequest\x1a .apiserver.v1.GetSessionResponse\"J\x92A.\n" +
	"\f会话管理\x12\x12获取会话详情*\n" +
	"GetSession\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/sessions/{id}\x12\x9e\x01\n" +
	"\fListSessions\x12!.apiserver.v1.ListSessionsRequest\x1a\".apiserver.v1.ListSessionsResponse\"G\x92A0\n" +
	"\f会话管理\x12\x12获取会话列表*\fListSessions\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/sessions\x12\xa4\x01\n" +
	"\rUpdateSession\x12\".apiserver.v1.UpdateSessionRequest\x1a#.apiserver.v1.UpdateSessionResponse\"J\x92A+\n" +
	"\f会话管理\x12\f更新会话*\rUpdateSession\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/sessions/{id}\x12\xa1\x01\n" +
	"\rDeleteSession\x12\".apiserver.v1.DeleteSessionRequest\x1a#.apiserver.v1.DeleteSessionResponse\"G\x92A+\n" +
	"\f会话管理\x12\f删除会话*\rDeleteSession\x82\xd3\xe4\x93\x02\x13*\x11/v1/sessions/{id}\x12\xc4\x01\n" +
	"\x13CreateKnowledgeBase\x12(.apiserver.v1.CreateKnowledgeBaseRequest\x1a).apiserver.v1.CreateKnowledgeBaseResponse\"X\x92A7\n" +
	"\x0f知识库管理\x12\x0f创建知识库*\x13CreateKnowledgeBase\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/knowledge-bases\x12\xc0\x01\n" +
	"\x10GetKnowledgeBase\x12%.apiserver.v1.GetKnowledgeBaseRequest\x1a&.apiserver.v1.GetKnowledgeBaseResponse\"]\x92A:\n" +
	"\x0f知识库管理\x12\x15获取知识库详情*\x10GetKnowledgeBase\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/knowledge-bases/{id}\x12\xc3\x01\n" +
	"\x12ListKnowledgeBases\x12'.apiserver.v1.ListKnowledgeBasesRequest\x1a(.apiserver.v1.ListKnowledgeBasesResponse\"Z\x92A<\n" +
	"\x0f知识库管理\x12\x15获取知识库列表*\x12ListKnowledgeBases\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/knowledge-bases\x12\xc9\x01\n" +
	"\x13UpdateKnowledgeBase\x12(.apiserver.v1.UpdateKnowledgeBaseRequest\x1a).apiserver.v1.UpdateKnowledgeBaseResponse\"]\x92A7\n" +
	"\x0f知识库管理\x12\x0f更新知识库*\x13UpdateKnowledgeBase\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/knowledge-bases/{id}\x12\xc6\x01\n" +
	"\x13DeleteKnowledgeBase\x12(.apiserver.v1.DeleteKnowledgeBaseRequest\x1a).apiserver.v1.DeleteKnowledgeBaseResponse\"Z\x92A7\n" +
	"\x0f知识库管理\x12\x0f删除知识库*\x13DeleteKnowledgeBase\x82\xd3\xe4\x93\x02\x1a*\x18/v1/knowledge-bases/{id}\x12\xc7\x01\n" +
	"\x11GetKnowledgeStats\x12&.apiserver.v1.GetKnowledgeStatsRequest\x1a$.apiserver.v1.KnowledgeStatsResponse\"d\x92A;\n" +
	"\x0f知识库管理\x12\x15获取知识库统计*\x11GetKnowledgeStats\x82\xd3\xe4\x93\x02 \x12\x1e/v1/knowledge-bases/{id}/stats\x12\xc2\x01\n" +
	"\x0eListKnowledges\x12#.apiserver.v1.ListKnowledgesRequest\x1a$.apiserver.v1.ListKnowledgesResponse\"e\x92A5\n" +
	"\x0f知识库管理\x12\x12获取知识列表*\x0eListKnowledges\x82\xd3\xe4\x93\x02'\x12%/v1/knowledge-bases/{kb_id}/knowledge\x12\xad\x01\n" +
	"\x0fDeleteKnowledge\x12$.apiserver.v1.DeleteKnowledgeRequest\x1a%.apiserver.v1.DeleteKnowledgeResponse\"M\x92A0\n" +
	"\x0f知识库管理\x12\f删除知识*\x0fDeleteKnowledge\x82\xd3\xe4\x93\x02\x14*\x12/v1/knowledge/{id}B\x9c\x02\x92A\xd7\x01\x12\xad\x01\n" +
	"\reino-show API\"L\n" +
	"\x10eino-show 项目\x12&https://github.com/ashwinyue/eino-show\x1a\x10stary99c@163.com*I\n" +
	"\vMIT License\x12:https://github.com/ashwinyue/eino-show/blob/master/LICENSE2\x031.0*\x01\x022\x10application/json:\x10application/jsonZ?github.com/ashwinyue/eino-show/pkg/api/apiserver/v1;apiserverv1b\x06proto3"

var file_apiserver_v1_apiserver_proto_goTypes = []any{
	(*emptypb.Empty)(nil),               // 0: google.protobuf.Empty
	(*LoginRequest)(nil),                // 1: apiserver.v1.LoginRequest
	(*RefreshTokenRequest)(nil),         // 2: apiserver.v1.RefreshTokenRequest
	(*ChangePasswordRequest)(nil),       // 3: apiserver.v1.ChangePasswordRequest
	(*CreateUserRequest)(nil),           // 4: apiserver.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),           // 5: apiserver.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),           // 6: apiserver.v1.DeleteUserRequest
	(*GetUserRequest)(nil),              // 7: apiserver.v1.GetUserRequest
	(*ListUserRequest)(nil),             // 8: apiserver.v1.ListUserRequest
	(*CreatePostRequest)(nil),           // 9: apiserver.v1.CreatePostRequest
	(*UpdatePostRequest)(nil),           // 10: apiserver.v1.UpdatePostRequest
	(*DeletePostRequest)(nil),           // 11: apiserver.v1.DeletePostRequest
	(*GetPostRequest)(nil),              // 12: apiserver.v1.GetPostRequest
	(*ListPostRequest)(nil),             // 13: apiserver.v1.ListPostRequest
	(*ListAgentsRequest)(nil),           // 14: apiserver.v1.ListAgentsRequest
	(*GetAgentRequest)(nil),             // 15: apiserver.v1.GetAgentRequest
	(*CreateAgentRequest)(nil),          // 16: apiserver.v1.CreateAgentRequest
	(*UpdateAgentRequest)(nil),          // 17: apiserver.v1.UpdateAgentRequest
	(*DeleteAgentRequest)(nil),          // 18: apiserver.v1.DeleteAgentRequest
	(*ListBuiltinAgentsRequest)(nil),    // 19: apiserver.v1.ListBuiltinAgentsRequest
	(*CreateSessionRequest)(nil),        // 20: apiserver.v1.CreateSessionRequest
	(*GetSessionRequest)(nil),           // 21: apiserver.v1.GetSessionRequest
	(*ListSessionsRequest)(nil),         // 22: apiserver.v1.ListSessionsRequest
	(*UpdateSessionRequest)(nil),        // 23: apiserver.v1.UpdateSessionRequest
	(*DeleteSessionRequest)(nil),        // 24: apiserver.v1.DeleteSessionRequest
	(*CreateKnowledgeBaseRequest)(nil),  // 25: apiserver.v1.CreateKnowledgeBaseRequest
	(*GetKnowledgeBaseRequest)(nil),     // 26: apiserver.v1.GetKnowledgeBaseRequest
	(*ListKnowledgeBasesRequest)(nil),   // 27: apiserver.v1.ListKnowledgeBasesRequest
	(*UpdateKnowledgeBaseRequest)(nil),  // 28: apiserver.v1.UpdateKnowledgeBaseRequest
	(*DeleteKnowledgeBaseRequest)(nil),  // 29: apiserver.v1.DeleteKnowledgeBaseRequest
	(*GetKnowledgeStatsRequest)(nil),    // 30: apiserver.v1.GetKnowledgeStatsRequest
	(*ListKnowledgesRequest)(nil),       // 31: apiserver.v1.ListKnowledgesRequest
	(*DeleteKnowledgeRequest)(nil),      // 32: apiserver.v1.DeleteKnowledgeRequest
	(*HealthzResponse)(nil),             // 33: apiserver.v1.HealthzResponse
	(*LoginResponse)(nil),               // 34: apiserver.v1.LoginResponse
	(*RefreshTokenResponse)(nil),        // 35: apiserver.v1.RefreshTokenResponse
	(*ChangePasswordResponse)(nil),      // 36: apiserver.v1.ChangePasswordResponse
	(*CreateUserResponse)(nil),          // 37: apiserver.v1.CreateUserResponse
	(*UpdateUserResponse)(nil),          // 38: apiserver.v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),          // 39: apiserver.v1.DeleteUserResponse
	(*GetUserResponse)(nil),             // 40: apiserver.v1.GetUserResponse
	(*ListUserResponse)(nil),            // 41: apiserver.v1.ListUserResponse
	(*CreatePostResponse)(nil),          // 42: apiserver.v1.CreatePostResponse
	(*UpdatePostResponse)(nil),          // 43: apiserver.v1.UpdatePostResponse
	(*DeletePostResponse)(nil),          // 44: apiserver.v1.DeletePostResponse
	(*GetPostResponse)(nil),             // 45: apiserver.v1.GetPostResponse
	(*ListPostResponse)(nil),            // 46: apiserver.v1.ListPostResponse
	(*ListAgentsResponse)(nil),          // 47: apiserver.v1.ListAgentsResponse
	(*GetAgentResponse)(nil),            // 48: apiserver.v1.GetAgentResponse
	(*CreateAgentResponse)(nil),         // 49: apiserver.v1.CreateAgentResponse
	(*UpdateAgentResponse)(nil),         // 50: apiserver.v1.UpdateAgentResponse
	(*DeleteAgentResponse)(nil),         // 51: apiserver.v1.DeleteAgentResponse
	(*ListBuiltinAgentsResponse)(nil),   // 52: apiserver.v1.ListBuiltinAgentsResponse
	(*CreateSessionResponse)(nil),       // 53: apiserver.v1.CreateSessionResponse
	(*GetSessionResponse)(nil),          // 54: apiserver.v1.GetSessionResponse
	(*ListSessionsResponse)(nil),        // 55: apiserver.v1.ListSessionsResponse
	(*UpdateSessionResponse)(nil),       // 56: apiserver.v1.UpdateSessionResponse
	(*DeleteSessionResponse)(nil),       // 57: apiserver.v1.DeleteSessionResponse
	(*CreateKnowledgeBaseResponse)(nil), // 58: apiserver.v1.CreateKnowledgeBaseResponse
	(*GetKnowledgeBaseResponse)(nil),    // 59: apiserver.v1.GetKnowledgeBaseResponse
	(*ListKnowledgeBasesResponse)(nil),  // 60: apiserver.v1.ListKnowledgeBasesResponse
	(*UpdateKnowledgeBaseResponse)(nil), // 61: apiserver.v1.UpdateKnowledgeBaseResponse
	(*DeleteKnowledgeBaseResponse)(nil), // 62: apiserver.v1.DeleteKnowledgeBaseResponse
	(*KnowledgeStatsResponse)(nil),      // 63: apiserver.v1.KnowledgeStatsResponse
	(*ListKnowledgesResponse)(nil),      // 64: apiserver.v1.ListKnowledgesResponse
	(*DeleteKnowledgeResponse)(nil),     // 65: apiserver.v1.DeleteKnowledgeResponse
}
var file_apiserver_v1_apiserver_proto_depIdxs = []int32{
	0,  // 0: apiserver.v1.MiniBlog.Healthz:input_type -> google.protobuf.Empty
	1,  // 1: apiserver.v1.MiniBlog.Login:input_type -> apiserver.v1.LoginRequest
	2,  // 2: apiserver.v1.MiniBlog.RefreshToken:input_type -> apiserver.v1.RefreshTokenRequest
	3,  // 3: apiserver.v1.MiniBlog.ChangePassword:input_type -> apiserver.v1.ChangePasswordRequest
	4,  // 4: apiserver.v1.MiniBlog.CreateUser:input_type -> apiserver.v1.CreateUserRequest
	5,  // 5: apiserver.v1.MiniBlog.UpdateUser:input_type -> apiserver.v1.UpdateUserRequest
	6,  // 6: apiserver.v1.MiniBlog.DeleteUser:input_type -> apiserver.v1.DeleteUserRequest
	7,  // 7: apiserver.v1.MiniBlog.GetUser:input_type -> apiserver.v1.GetUserRequest
	8,  // 8: apiserver.v1.MiniBlog.ListUser:input_type -> apiserver.v1.ListUserRequest
	9,  // 9: apiserver.v1.MiniBlog.CreatePost:input_type -> apiserver.v1.CreatePostRequest
	10, // 10: apiserver.v1.MiniBlog.UpdatePost:input_type -> apiserver.v1.UpdatePostRequest
	11, // 11: apiserver.v1.MiniBlog.DeletePost:input_type -> apiserver.v1.DeletePostRequest
	12, // 12: apiserver.v1.MiniBlog.GetPost:input_type -> apiserver.v1.GetPostRequest
	13, // 13: apiserver.v1.MiniBlog.ListPost:input_type -> apiserver.v1.ListPostRequest
	14, // 14: apiserver.v1.MiniBlog.ListAgents:input_type -> apiserver.v1.ListAgentsRequest
	15, // 15: apiserver.v1.MiniBlog.GetAgent:input_type -> apiserver.v1.GetAgentRequest
	16, // 16: apiserver.v1.MiniBlog.CreateAgent:input_type -> apiserver.v1.CreateAgentRequest
	17, // 17: apiserver.v1.MiniBlog.UpdateAgent:input_type -> apiserver.v1.UpdateAgentRequest
	18, // 18: apiserver.v1.MiniBlog.DeleteAgent:input_type -> apiserver.v1.DeleteAgentRequest
	19, // 19: apiserver.v1.MiniBlog.ListBuiltinAgents:input_type -> apiserver.v1.ListBuiltinAgentsRequest
	20, // 20: apiserver.v1.MiniBlog.CreateSession:input_type -> apiserver.v1.CreateSessionRequest
	21, // 21: apiserver.v1.MiniBlog.GetSession:input_type -> apiserver.v1.GetSessionRequest
	22, // 22: apiserver.v1.MiniBlog.ListSessions:input_type -> apiserver.v1.ListSessionsRequest
	23, // 23: apiserver.v1.MiniBlog.UpdateSession:input_type -> apiserver.v1.UpdateSessionRequest
	24, // 24: apiserver.v1.MiniBlog.DeleteSession:input_type -> apiserver.v1.DeleteSessionRequest
	25, // 25: apiserver.v1.MiniBlog.CreateKnowledgeBase:input_type -> apiserver.v1.CreateKnowledgeBaseRequest
	26, // 26: apiserver.v1.MiniBlog.GetKnowledgeBase:input_type -> apiserver.v1.GetKnowledgeBaseRequest
	27, // 27: apiserver.v1.MiniBlog.ListKnowledgeBases:input_type -> apiserver.v1.ListKnowledgeBasesRequest
	28, // 28: apiserver.v1.MiniBlog.UpdateKnowledgeBase:input_type -> apiserver.v1.UpdateKnowledgeBaseRequest
	29, // 29: apiserver.v1.MiniBlog.DeleteKnowledgeBase:input_type -> apiserver.v1.DeleteKnowledgeBaseRequest
	30, // 30: apiserver.v1.MiniBlog.GetKnowledgeStats:input_type -> apiserver.v1.GetKnowledgeStatsRequest
	31, // 31: apiserver.v1.MiniBlog.ListKnowledges:input_type -> apiserver.v1.ListKnowledgesRequest
	32, // 32: apiserver.v1.MiniBlog.DeleteKnowledge:input_type -> apiserver.v1.DeleteKnowledgeRequest
	33, // 33: apiserver.v1.MiniBlog.Healthz:output_type -> apiserver.v1.HealthzResponse
	34, // 34: apiserver.v1.MiniBlog.Login:output_type -> apiserver.v1.LoginResponse
	35, // 35: apiserver.v1.MiniBlog.RefreshToken:output_type -> apiserver.v1.RefreshTokenResponse
	36, // 36: apiserver.v1.MiniBlog.ChangePassword:output_type -> apiserver.v1.ChangePasswordResponse
	37, // 37: apiserver.v1.MiniBlog.CreateUser:output_type -> apiserver.v1.CreateUserResponse
	38, // 38: apiserver.v1.MiniBlog.UpdateUser:output_type -> apiserver.v1.UpdateUserResponse
	39, // 39: apiserver.v1.MiniBlog.DeleteUser:output_type -> apiserver.v1.DeleteUserResponse
	40, // 40: apiserver.v1.MiniBlog.GetUser:output_type -> apiserver.v1.GetUserResponse
	41, // 41: apiserver.v1.MiniBlog.ListUser:output_type -> apiserver.v1.ListUserResponse
	42, // 42: apiserver.v1.MiniBlog.CreatePost:output_type -> apiserver.v1.CreatePostResponse
	43, // 43: apiserver.v1.MiniBlog.UpdatePost:output_type -> apiserver.v1.UpdatePostResponse
	44, // 44: apiserver.v1.MiniBlog.DeletePost:output_type -> apiserver.v1.DeletePostResponse
	45, // 45: apiserver.v1.MiniBlog.GetPost:output_type -> apiserver.v1.GetPostResponse
	46, // 46: apiserver.v1.MiniBlog.ListPost:output_type -> apiserver.v1.ListPostResponse
	47, // 47: apiserver.v1.MiniBlog.ListAgents:output_type -> apiserver.v1.ListAgentsResponse
	48, // 48: apiserver.v1.MiniBlog.GetAgent:output_type -> apiserver.v1.GetAgentResponse
	49, // 49: apiserver.v1.MiniBlog.CreateAgent:output_type -> apiserver.v1.CreateAgentResponse
	50, // 50: apiserver.v1.MiniBlog.UpdateAgent:output_type -> apiserver.v1.UpdateAgentResponse
	51, // 51: apiserver.v1.MiniBlog.DeleteAgent:output_type -> apiserver.v1.DeleteAgentResponse
	52, // 52: apiserver.v1.MiniBlog.ListBuiltinAgents:output_type -> apiserver.v1.ListBuiltinAgentsResponse
	53, // 53: apiserver.v1.MiniBlog.CreateSession:output_type -> apiserver.v1.CreateSessionResponse
	54, // 54: apiserver.v1.MiniBlog.GetSession:output_type -> apiserver.v1.GetSessionResponse
	55, // 55: apiserver.v1.MiniBlog.ListSessions:output_type -> apiserver.v1.ListSessionsResponse
	56, // 56: apiserver.v1.MiniBlog.UpdateSession:output_type -> apiserver.v1.UpdateSessionResponse
	57, // 57: apiserver.v1.MiniBlog.DeleteSession:output_type -> apiserver.v1.DeleteSessionResponse
	58, // 58: apiserver.v1.MiniBlog.CreateKnowledgeBase:output_type -> apiserver.v1.CreateKnowledgeBaseResponse
	59, // 59: apiserver.v1.MiniBlog.GetKnowledgeBase:output_type -> apiserver.v1.GetKnowledgeBaseResponse
	60, // 60: apiserver.v1.MiniBlog.ListKnowledgeBases:output_type -> apiserver.v1.ListKnowledgeBasesResponse
	61, // 61: apiserver.v1.MiniBlog.UpdateKnowledgeBase:output_type -> apiserver.v1.UpdateKnowledgeBaseResponse
	62, // 62: apiserver.v1.MiniBlog.DeleteKnowledgeBase:output_type -> apiserver.v1.DeleteKnowledgeBaseResponse
	63, // 63: apiserver.v1.MiniBlog.GetKnowledgeStats:output_type -> apiserver.v1.KnowledgeStatsResponse
	64, // 64: apiserver.v1.MiniBlog.ListKnowledges:output_type -> apiserver.v1.ListKnowledgesResponse
	65, // 65: apiserver.v1.MiniBlog.DeleteKnowledge:output_type -> apiserver.v1.DeleteKnowledgeResponse
	33, // [33:66] is the sub-list for method output_type
	0,  // [0:33] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_v1_apiserver_proto_init() }
func file_apiserver_v1_apiserver_proto_init() {
	if File_apiserver_v1_apiserver_proto != nil {
		return
	}
	file_apiserver_v1_healthz_proto_init()
	file_apiserver_v1_post_proto_init()
	file_apiserver_v1_user_proto_init()
	file_apiserver_v1_agent_proto_init()
	file_apiserver_v1_session_proto_init()
	file_apiserver_v1_knowledge_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_apiserver_proto_rawDesc), len(file_apiserver_v1_apiserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiserver_v1_apiserver_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_apiserver_proto_depIdxs,
	}.Build()
	File_apiserver_v1_apiserver_proto = out.File
	file_apiserver_v1_apiserver_proto_goTypes = nil
	file_apiserver_v1_apiserver_proto_depIdxs = nil
}
