// Copyright 2026 阿斯温月 <stary99c@163.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/ashwinyue/eino-show. The professional
// version of this repository is https://github.com/onexstack/onex.

// Knowledge API 定义，包含知识库管理的 RPC 接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apiserver/v1/knowledge.proto

package apiserverv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KnowledgeBase 知识库
type KnowledgeBase struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	Id                    string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ChunkingConfig        *KnowledgeChunkingConfig `protobuf:"bytes,4,opt,name=chunking_config,json=chunkingConfig,proto3" json:"chunking_config,omitempty"`
	ImageProcessingConfig *KnowledgeImageConfig    `protobuf:"bytes,5,opt,name=image_processing_config,json=imageProcessingConfig,proto3" json:"image_processing_config,omitempty"`
	EmbeddingModelId      string                   `protobuf:"bytes,6,opt,name=embedding_model_id,json=embeddingModelId,proto3" json:"embedding_model_id,omitempty"`
	SummaryModelId        string                   `protobuf:"bytes,7,opt,name=summary_model_id,json=summaryModelId,proto3" json:"summary_model_id,omitempty"`
	RerankModelId         string                   `protobuf:"bytes,8,opt,name=rerank_model_id,json=rerankModelId,proto3" json:"rerank_model_id,omitempty"`
	CreatedAt             *timestamppb.Timestamp   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *KnowledgeBase) Reset() {
	*x = KnowledgeBase{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBase) ProtoMessage() {}

func (x *KnowledgeBase) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBase.ProtoReflect.Descriptor instead.
func (*KnowledgeBase) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeBase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeBase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowledgeBase) GetChunkingConfig() *KnowledgeChunkingConfig {
	if x != nil {
		return x.ChunkingConfig
	}
	return nil
}

func (x *KnowledgeBase) GetImageProcessingConfig() *KnowledgeImageConfig {
	if x != nil {
		return x.ImageProcessingConfig
	}
	return nil
}

func (x *KnowledgeBase) GetEmbeddingModelId() string {
	if x != nil {
		return x.EmbeddingModelId
	}
	return ""
}

func (x *KnowledgeBase) GetSummaryModelId() string {
	if x != nil {
		return x.SummaryModelId
	}
	return ""
}

func (x *KnowledgeBase) GetRerankModelId() string {
	if x != nil {
		return x.RerankModelId
	}
	return ""
}

func (x *KnowledgeBase) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeBase) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// KnowledgeChunkingConfig 文档分块配置
type KnowledgeChunkingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkSize     int32                  `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkOverlap  int32                  `protobuf:"varint,2,opt,name=chunk_overlap,json=chunkOverlap,proto3" json:"chunk_overlap,omitempty"`
	SplitMarkers  []string               `protobuf:"bytes,3,rep,name=split_markers,json=splitMarkers,proto3" json:"split_markers,omitempty"`
	KeepSeparator bool                   `protobuf:"varint,4,opt,name=keep_separator,json=keepSeparator,proto3" json:"keep_separator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeChunkingConfig) Reset() {
	*x = KnowledgeChunkingConfig{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeChunkingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeChunkingConfig) ProtoMessage() {}

func (x *KnowledgeChunkingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeChunkingConfig.ProtoReflect.Descriptor instead.
func (*KnowledgeChunkingConfig) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *KnowledgeChunkingConfig) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *KnowledgeChunkingConfig) GetChunkOverlap() int32 {
	if x != nil {
		return x.ChunkOverlap
	}
	return 0
}

func (x *KnowledgeChunkingConfig) GetSplitMarkers() []string {
	if x != nil {
		return x.SplitMarkers
	}
	return nil
}

func (x *KnowledgeChunkingConfig) GetKeepSeparator() bool {
	if x != nil {
		return x.KeepSeparator
	}
	return false
}

// KnowledgeImageConfig 图像处理配置
type KnowledgeImageConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EnableMultimodal bool                   `protobuf:"varint,1,opt,name=enable_multimodal,json=enableMultimodal,proto3" json:"enable_multimodal,omitempty"`
	ModelId          string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KnowledgeImageConfig) Reset() {
	*x = KnowledgeImageConfig{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeImageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeImageConfig) ProtoMessage() {}

func (x *KnowledgeImageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeImageConfig.ProtoReflect.Descriptor instead.
func (*KnowledgeImageConfig) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *KnowledgeImageConfig) GetEnableMultimodal() bool {
	if x != nil {
		return x.EnableMultimodal
	}
	return false
}

func (x *KnowledgeImageConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// Knowledge 知识项
type Knowledge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	KnowledgeBaseId  string                 `protobuf:"bytes,2,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Source           string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ParseStatus      string                 `protobuf:"bytes,7,opt,name=parse_status,json=parseStatus,proto3" json:"parse_status,omitempty"`
	EnableStatus     string                 `protobuf:"bytes,8,opt,name=enable_status,json=enableStatus,proto3" json:"enable_status,omitempty"`
	EmbeddingModelId string                 `protobuf:"bytes,9,opt,name=embedding_model_id,json=embeddingModelId,proto3" json:"embedding_model_id,omitempty"`
	FileName         string                 `protobuf:"bytes,10,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType         string                 `protobuf:"bytes,11,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Knowledge) Reset() {
	*x = Knowledge{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Knowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Knowledge) ProtoMessage() {}

func (x *Knowledge) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Knowledge.ProtoReflect.Descriptor instead.
func (*Knowledge) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *Knowledge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Knowledge) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *Knowledge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Knowledge) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Knowledge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Knowledge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Knowledge) GetParseStatus() string {
	if x != nil {
		return x.ParseStatus
	}
	return ""
}

func (x *Knowledge) GetEnableStatus() string {
	if x != nil {
		return x.EnableStatus
	}
	return ""
}

func (x *Knowledge) GetEmbeddingModelId() string {
	if x != nil {
		return x.EmbeddingModelId
	}
	return ""
}

func (x *Knowledge) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Knowledge) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Knowledge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Knowledge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateKnowledgeBaseRequest 创建知识库请求
type CreateKnowledgeBaseRequest struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	Name                  string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ChunkingConfig        *KnowledgeChunkingConfig `protobuf:"bytes,3,opt,name=chunking_config,json=chunkingConfig,proto3" json:"chunking_config,omitempty"`
	ImageProcessingConfig *KnowledgeImageConfig    `protobuf:"bytes,4,opt,name=image_processing_config,json=imageProcessingConfig,proto3" json:"image_processing_config,omitempty"`
	EmbeddingModelId      string                   `protobuf:"bytes,5,opt,name=embedding_model_id,json=embeddingModelId,proto3" json:"embedding_model_id,omitempty"`
	SummaryModelId        string                   `protobuf:"bytes,6,opt,name=summary_model_id,json=summaryModelId,proto3" json:"summary_model_id,omitempty"`
	RerankModelId         string                   `protobuf:"bytes,7,opt,name=rerank_model_id,json=rerankModelId,proto3" json:"rerank_model_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseRequest) Reset() {
	*x = CreateKnowledgeBaseRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetChunkingConfig() *KnowledgeChunkingConfig {
	if x != nil {
		return x.ChunkingConfig
	}
	return nil
}

func (x *CreateKnowledgeBaseRequest) GetImageProcessingConfig() *KnowledgeImageConfig {
	if x != nil {
		return x.ImageProcessingConfig
	}
	return nil
}

func (x *CreateKnowledgeBaseRequest) GetEmbeddingModelId() string {
	if x != nil {
		return x.EmbeddingModelId
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetSummaryModelId() string {
	if x != nil {
		return x.SummaryModelId
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetRerankModelId() string {
	if x != nil {
		return x.RerankModelId
	}
	return ""
}

// CreateKnowledgeBaseResponse 创建知识库响应
type CreateKnowledgeBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseResponse) Reset() {
	*x = CreateKnowledgeBaseResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseResponse) ProtoMessage() {}

func (x *CreateKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *CreateKnowledgeBaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateKnowledgeBaseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeBaseResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetKnowledgeBaseRequest 获取知识库请求
type GetKnowledgeBaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeBaseRequest) Reset() {
	*x = GetKnowledgeBaseRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeBaseRequest) ProtoMessage() {}

func (x *GetKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *GetKnowledgeBaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetKnowledgeBaseResponse 获取知识库响应
type GetKnowledgeBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBase *KnowledgeBase         `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeBaseResponse) Reset() {
	*x = GetKnowledgeBaseResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeBaseResponse) ProtoMessage() {}

func (x *GetKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *GetKnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBase {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

// ListKnowledgeBasesRequest 获取知识库列表请求
type ListKnowledgeBasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeBasesRequest) Reset() {
	*x = ListKnowledgeBasesRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesRequest) ProtoMessage() {}

func (x *ListKnowledgeBasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

// ListKnowledgeBasesResponse 获取知识库列表响应
type ListKnowledgeBasesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBases []*KnowledgeBase       `protobuf:"bytes,1,rep,name=knowledge_bases,json=knowledgeBases,proto3" json:"knowledge_bases,omitempty"`
	Total          int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListKnowledgeBasesResponse) Reset() {
	*x = ListKnowledgeBasesResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesResponse) ProtoMessage() {}

func (x *ListKnowledgeBasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesResponse.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *ListKnowledgeBasesResponse) GetKnowledgeBases() []*KnowledgeBase {
	if x != nil {
		return x.KnowledgeBases
	}
	return nil
}

func (x *ListKnowledgeBasesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateKnowledgeBaseRequest 更新知识库请求
type UpdateKnowledgeBaseRequest struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	Id                    string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  *string                  `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description           *string                  `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ChunkingConfig        *KnowledgeChunkingConfig `protobuf:"bytes,4,opt,name=chunking_config,json=chunkingConfig,proto3,oneof" json:"chunking_config,omitempty"`
	ImageProcessingConfig *KnowledgeImageConfig    `protobuf:"bytes,5,opt,name=image_processing_config,json=imageProcessingConfig,proto3,oneof" json:"image_processing_config,omitempty"`
	EmbeddingModelId      *string                  `protobuf:"bytes,6,opt,name=embedding_model_id,json=embeddingModelId,proto3,oneof" json:"embedding_model_id,omitempty"`
	SummaryModelId        *string                  `protobuf:"bytes,7,opt,name=summary_model_id,json=summaryModelId,proto3,oneof" json:"summary_model_id,omitempty"`
	RerankModelId         *string                  `protobuf:"bytes,8,opt,name=rerank_model_id,json=rerankModelId,proto3,oneof" json:"rerank_model_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateKnowledgeBaseRequest) Reset() {
	*x = UpdateKnowledgeBaseRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeBaseRequest) ProtoMessage() {}

func (x *UpdateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateKnowledgeBaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateKnowledgeBaseRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateKnowledgeBaseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateKnowledgeBaseRequest) GetChunkingConfig() *KnowledgeChunkingConfig {
	if x != nil {
		return x.ChunkingConfig
	}
	return nil
}

func (x *UpdateKnowledgeBaseRequest) GetImageProcessingConfig() *KnowledgeImageConfig {
	if x != nil {
		return x.ImageProcessingConfig
	}
	return nil
}

func (x *UpdateKnowledgeBaseRequest) GetEmbeddingModelId() string {
	if x != nil && x.EmbeddingModelId != nil {
		return *x.EmbeddingModelId
	}
	return ""
}

func (x *UpdateKnowledgeBaseRequest) GetSummaryModelId() string {
	if x != nil && x.SummaryModelId != nil {
		return *x.SummaryModelId
	}
	return ""
}

func (x *UpdateKnowledgeBaseRequest) GetRerankModelId() string {
	if x != nil && x.RerankModelId != nil {
		return *x.RerankModelId
	}
	return ""
}

// UpdateKnowledgeBaseResponse 更新知识库响应
type UpdateKnowledgeBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKnowledgeBaseResponse) Reset() {
	*x = UpdateKnowledgeBaseResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeBaseResponse) ProtoMessage() {}

func (x *UpdateKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateKnowledgeBaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateKnowledgeBaseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKnowledgeBaseResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DeleteKnowledgeBaseRequest 删除知识库请求
type DeleteKnowledgeBaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeBaseRequest) Reset() {
	*x = DeleteKnowledgeBaseRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseRequest) ProtoMessage() {}

func (x *DeleteKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteKnowledgeBaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteKnowledgeBaseResponse 删除知识库响应
type DeleteKnowledgeBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeBaseResponse) Reset() {
	*x = DeleteKnowledgeBaseResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseResponse) ProtoMessage() {}

func (x *DeleteKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteKnowledgeBaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteKnowledgeBaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetKnowledgeStatsRequest 获取知识库统计请求
type GetKnowledgeStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeStatsRequest) Reset() {
	*x = GetKnowledgeStatsRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeStatsRequest) ProtoMessage() {}

func (x *GetKnowledgeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeStatsRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeStatsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *GetKnowledgeStatsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// KnowledgeStatsResponse 知识库统计响应
type KnowledgeStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeCount int64                  `protobuf:"varint,1,opt,name=knowledge_count,json=knowledgeCount,proto3" json:"knowledge_count,omitempty"`
	ChunkCount     int64                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnowledgeStatsResponse) Reset() {
	*x = KnowledgeStatsResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeStatsResponse) ProtoMessage() {}

func (x *KnowledgeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeStatsResponse.ProtoReflect.Descriptor instead.
func (*KnowledgeStatsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *KnowledgeStatsResponse) GetKnowledgeCount() int64 {
	if x != nil {
		return x.KnowledgeCount
	}
	return 0
}

func (x *KnowledgeStatsResponse) GetChunkCount() int64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// ListKnowledgesRequest 获取知识列表请求
type ListKnowledgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KbId          string                 `protobuf:"bytes,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgesRequest) Reset() {
	*x = ListKnowledgesRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgesRequest) ProtoMessage() {}

func (x *ListKnowledgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgesRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{16}
}

func (x *ListKnowledgesRequest) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

// ListKnowledgesResponse 获取知识列表响应
type ListKnowledgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Knowledge     []*Knowledge           `protobuf:"bytes,1,rep,name=knowledge,proto3" json:"knowledge,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgesResponse) Reset() {
	*x = ListKnowledgesResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgesResponse) ProtoMessage() {}

func (x *ListKnowledgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgesResponse.ProtoReflect.Descriptor instead.
func (*ListKnowledgesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{17}
}

func (x *ListKnowledgesResponse) GetKnowledge() []*Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

func (x *ListKnowledgesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// DeleteKnowledgeRequest 删除知识项请求
type DeleteKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeRequest) Reset() {
	*x = DeleteKnowledgeRequest{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeRequest) ProtoMessage() {}

func (x *DeleteKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteKnowledgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteKnowledgeResponse 删除知识项响应
type DeleteKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeResponse) Reset() {
	*x = DeleteKnowledgeResponse{}
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeResponse) ProtoMessage() {}

func (x *DeleteKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_knowledge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_knowledge_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteKnowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteKnowledgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_apiserver_v1_knowledge_proto protoreflect.FileDescriptor

const file_apiserver_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1capiserver/v1/knowledge.proto\x12\fapiserver.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf7\x03\n" +
	"\rKnowledgeBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12N\n" +
	"\x0fchunking_config\x18\x04 \x01(\v2%.apiserver.v1.KnowledgeChunkingConfigR\x0echunkingConfig\x12Z\n" +
	"\x17image_processing_config\x18\x05 \x01(\v2\".apiserver.v1.KnowledgeImageConfigR\x15imageProcessingConfig\x12,\n" +
	"\x12embedding_model_id\x18\x06 \x01(\tR\x10embeddingModelId\x12(\n" +
	"\x10summary_model_id\x18\a \x01(\tR\x0esummaryModelId\x12&\n" +
	"\x0frerank_model_id\x18\b \x01(\tR\rrerankModelId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa9\x01\n" +
	"\x17KnowledgeChunkingConfig\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\x05R\tchunkSize\x12#\n" +
	"\rchunk_overlap\x18\x02 \x01(\x05R\fchunkOverlap\x12#\n" +
	"\rsplit_markers\x18\x03 \x03(\tR\fsplitMarkers\x12%\n" +
	"\x0ekeep_separator\x18\x04 \x01(\bR\rkeepSeparator\"^\n" +
	"\x14KnowledgeImageConfig\x12+\n" +
	"\x11enable_multimodal\x18\x01 \x01(\bR\x10enableMultimodal\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"\xd1\x03\n" +
	"\tKnowledge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11knowledge_base_id\x18\x02 \x01(\tR\x0fknowledgeBaseId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12!\n" +
	"\fparse_status\x18\a \x01(\tR\vparseStatus\x12#\n" +
	"\renable_status\x18\b \x01(\tR\fenableStatus\x12,\n" +
	"\x12embedding_model_id\x18\t \x01(\tR\x10embeddingModelId\x12\x1b\n" +
	"\tfile_name\x18\n" +
	" \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\v \x01(\tR\bfileType\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfe\x02\n" +
	"\x1aCreateKnowledgeBaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12N\n" +
	"\x0fchunking_config\x18\x03 \x01(\v2%.apiserver.v1.KnowledgeChunkingConfigR\x0echunkingConfig\x12Z\n" +
	"\x17image_processing_config\x18\x04 \x01(\v2\".apiserver.v1.KnowledgeImageConfigR\x15imageProcessingConfig\x12,\n" +
	"\x12embedding_model_id\x18\x05 \x01(\tR\x10embeddingModelId\x12(\n" +
	"\x10summary_model_id\x18\x06 \x01(\tR\x0esummaryModelId\x12&\n" +
	"\x0frerank_model_id\x18\a \x01(\tR\rrerankModelId\"|\n" +
	"\x1bCreateKnowledgeBaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\x17GetKnowledgeBaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x18GetKnowledgeBaseResponse\x12B\n" +
	"\x0eknowledge_base\x18\x01 \x01(\v2\x1b.apiserver.v1.KnowledgeBaseR\rknowledgeBase\"\x1b\n" +
	"\x19ListKnowledgeBasesRequest\"x\n" +
	"\x1aListKnowledgeBasesResponse\x12D\n" +
	"\x0fknowledge_bases\x18\x01 \x03(\v2\x1b.apiserver.v1.KnowledgeBaseR\x0eknowledgeBases\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xba\x04\n" +
	"\x1aUpdateKnowledgeBaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12S\n" +
	"\x0fchunking_config\x18\x04 \x01(\v2%.apiserver.v1.KnowledgeChunkingConfigH\x02R\x0echunkingConfig\x88\x01\x01\x12_\n" +
	"\x17image_processing_config\x18\x05 \x01(\v2\".apiserver.v1.KnowledgeImageConfigH\x03R\x15imageProcessingConfig\x88\x01\x01\x121\n" +
	"\x12embedding_model_id\x18\x06 \x01(\tH\x04R\x10embeddingModelId\x88\x01\x01\x12-\n" +
	"\x10summary_model_id\x18\a \x01(\tH\x05R\x0esummaryModelId\x88\x01\x01\x12+\n" +
	"\x0frerank_model_id\x18\b \x01(\tH\x06R\rrerankModelId\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_chunking_configB\x1a\n" +
	"\x18_image_processing_configB\x15\n" +
	"\x13_embedding_model_idB\x13\n" +
	"\x11_summary_model_idB\x12\n" +
	"\x10_rerank_model_id\"|\n" +
	"\x1bUpdateKnowledgeBaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x1aDeleteKnowledgeBaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x1bDeleteKnowledgeBaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x18GetKnowledgeStatsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x16KnowledgeStatsResponse\x12'\n" +
	"\x0fknowledge_count\x18\x01 \x01(\x03R\x0eknowledgeCount\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x03R\n" +
	"chunkCount\",\n" +
	"\x15ListKnowledgesRequest\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\tR\x04kbId\"e\n" +
	"\x16ListKnowledgesResponse\x125\n" +
	"\tknowledge\x18\x01 \x03(\v2\x17.apiserver.v1.KnowledgeR\tknowledge\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"(\n" +
	"\x16DeleteKnowledgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x17DeleteKnowledgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBAZ?github.com/ashwinyue/eino-show/pkg/api/apiserver/v1;apiserverv1b\x06proto3"

var (
	file_apiserver_v1_knowledge_proto_rawDescOnce sync.Once
	file_apiserver_v1_knowledge_proto_rawDescData []byte
)

func file_apiserver_v1_knowledge_proto_rawDescGZIP() []byte {
	file_apiserver_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_knowledge_proto_rawDesc), len(file_apiserver_v1_knowledge_proto_rawDesc)))
	})
	return file_apiserver_v1_knowledge_proto_rawDescData
}

var file_apiserver_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_apiserver_v1_knowledge_proto_goTypes = []any{
	(*KnowledgeBase)(nil),               // 0: apiserver.v1.KnowledgeBase
	(*KnowledgeChunkingConfig)(nil),     // 1: apiserver.v1.KnowledgeChunkingConfig
	(*KnowledgeImageConfig)(nil),        // 2: apiserver.v1.KnowledgeImageConfig
	(*Knowledge)(nil),                   // 3: apiserver.v1.Knowledge
	(*CreateKnowledgeBaseRequest)(nil),  // 4: apiserver.v1.CreateKnowledgeBaseRequest
	(*CreateKnowledgeBaseResponse)(nil), // 5: apiserver.v1.CreateKnowledgeBaseResponse
	(*GetKnowledgeBaseRequest)(nil),     // 6: apiserver.v1.GetKnowledgeBaseRequest
	(*GetKnowledgeBaseResponse)(nil),    // 7: apiserver.v1.GetKnowledgeBaseResponse
	(*ListKnowledgeBasesRequest)(nil),   // 8: apiserver.v1.ListKnowledgeBasesRequest
	(*ListKnowledgeBasesResponse)(nil),  // 9: apiserver.v1.ListKnowledgeBasesResponse
	(*UpdateKnowledgeBaseRequest)(nil),  // 10: apiserver.v1.UpdateKnowledgeBaseRequest
	(*UpdateKnowledgeBaseResponse)(nil), // 11: apiserver.v1.UpdateKnowledgeBaseResponse
	(*DeleteKnowledgeBaseRequest)(nil),  // 12: apiserver.v1.DeleteKnowledgeBaseRequest
	(*DeleteKnowledgeBaseResponse)(nil), // 13: apiserver.v1.DeleteKnowledgeBaseResponse
	(*GetKnowledgeStatsRequest)(nil),    // 14: apiserver.v1.GetKnowledgeStatsRequest
	(*KnowledgeStatsResponse)(nil),      // 15: apiserver.v1.KnowledgeStatsResponse
	(*ListKnowledgesRequest)(nil),       // 16: apiserver.v1.ListKnowledgesRequest
	(*ListKnowledgesResponse)(nil),      // 17: apiserver.v1.ListKnowledgesResponse
	(*DeleteKnowledgeRequest)(nil),      // 18: apiserver.v1.DeleteKnowledgeRequest
	(*DeleteKnowledgeResponse)(nil),     // 19: apiserver.v1.DeleteKnowledgeResponse
	(*timestamppb.Timestamp)(nil),       // 20: google.protobuf.Timestamp
}
var file_apiserver_v1_knowledge_proto_depIdxs = []int32{
	1,  // 0: apiserver.v1.KnowledgeBase.chunking_config:type_name -> apiserver.v1.KnowledgeChunkingConfig
	2,  // 1: apiserver.v1.KnowledgeBase.image_processing_config:type_name -> apiserver.v1.KnowledgeImageConfig
	20, // 2: apiserver.v1.KnowledgeBase.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: apiserver.v1.KnowledgeBase.updated_at:type_name -> google.protobuf.Timestamp
	20, // 4: apiserver.v1.Knowledge.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: apiserver.v1.Knowledge.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: apiserver.v1.CreateKnowledgeBaseRequest.chunking_config:type_name -> apiserver.v1.KnowledgeChunkingConfig
	2,  // 7: apiserver.v1.CreateKnowledgeBaseRequest.image_processing_config:type_name -> apiserver.v1.KnowledgeImageConfig
	20, // 8: apiserver.v1.CreateKnowledgeBaseResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 9: apiserver.v1.GetKnowledgeBaseResponse.knowledge_base:type_name -> apiserver.v1.KnowledgeBase
	0,  // 10: apiserver.v1.ListKnowledgeBasesResponse.knowledge_bases:type_name -> apiserver.v1.KnowledgeBase
	1,  // 11: apiserver.v1.UpdateKnowledgeBaseRequest.chunking_config:type_name -> apiserver.v1.KnowledgeChunkingConfig
	2,  // 12: apiserver.v1.UpdateKnowledgeBaseRequest.image_processing_config:type_name -> apiserver.v1.KnowledgeImageConfig
	20, // 13: apiserver.v1.UpdateKnowledgeBaseResponse.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 14: apiserver.v1.ListKnowledgesResponse.knowledge:type_name -> apiserver.v1.Knowledge
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_apiserver_v1_knowledge_proto_init() }
func file_apiserver_v1_knowledge_proto_init() {
	if File_apiserver_v1_knowledge_proto != nil {
		return
	}
	file_apiserver_v1_knowledge_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_knowledge_proto_rawDesc), len(file_apiserver_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_knowledge_proto_msgTypes,
	}.Build()
	File_apiserver_v1_knowledge_proto = out.File
	file_apiserver_v1_knowledge_proto_goTypes = nil
	file_apiserver_v1_knowledge_proto_depIdxs = nil
}
