// Session API 定义，包含会话管理的 RPC 接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apiserver/v1/session.proto

package apiserverv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session 会话
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig   *SessionAgentConfig    `protobuf:"bytes,5,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	ContextConfig *SessionContextConfig  `protobuf:"bytes,6,opt,name=context_config,json=contextConfig,proto3" json:"context_config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_apiserver_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Session) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Session) GetAgentConfig() *SessionAgentConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *Session) GetContextConfig() *SessionContextConfig {
	if x != nil {
		return x.ContextConfig
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SessionAgentConfig 会话级别的 Agent 配置
type SessionAgentConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Mode             string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	KnowledgeBases   []string               `protobuf:"bytes,3,rep,name=knowledge_bases,json=knowledgeBases,proto3" json:"knowledge_bases,omitempty"`
	Temperature      float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxIterations    int32                  `protobuf:"varint,5,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	WebSearchEnabled bool                   `protobuf:"varint,6,opt,name=web_search_enabled,json=webSearchEnabled,proto3" json:"web_search_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionAgentConfig) Reset() {
	*x = SessionAgentConfig{}
	mi := &file_apiserver_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAgentConfig) ProtoMessage() {}

func (x *SessionAgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAgentConfig.ProtoReflect.Descriptor instead.
func (*SessionAgentConfig) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *SessionAgentConfig) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionAgentConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionAgentConfig) GetKnowledgeBases() []string {
	if x != nil {
		return x.KnowledgeBases
	}
	return nil
}

func (x *SessionAgentConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SessionAgentConfig) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *SessionAgentConfig) GetWebSearchEnabled() bool {
	if x != nil {
		return x.WebSearchEnabled
	}
	return false
}

// SessionContextConfig LLM 上下文管理配置
type SessionContextConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MaxMessages              int32                  `protobuf:"varint,1,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	CompressionThreshold     int32                  `protobuf:"varint,2,opt,name=compression_threshold,json=compressionThreshold,proto3" json:"compression_threshold,omitempty"`
	EnableContextCompression bool                   `protobuf:"varint,3,opt,name=enable_context_compression,json=enableContextCompression,proto3" json:"enable_context_compression,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SessionContextConfig) Reset() {
	*x = SessionContextConfig{}
	mi := &file_apiserver_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContextConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContextConfig) ProtoMessage() {}

func (x *SessionContextConfig) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContextConfig.ProtoReflect.Descriptor instead.
func (*SessionContextConfig) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionContextConfig) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

func (x *SessionContextConfig) GetCompressionThreshold() int32 {
	if x != nil {
		return x.CompressionThreshold
	}
	return 0
}

func (x *SessionContextConfig) GetEnableContextCompression() bool {
	if x != nil {
		return x.EnableContextCompression
	}
	return false
}

// CreateSessionRequest 创建会话请求
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig   *SessionAgentConfig    `protobuf:"bytes,4,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	ContextConfig *SessionContextConfig  `protobuf:"bytes,5,opt,name=context_config,json=contextConfig,proto3" json:"context_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_apiserver_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSessionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSessionRequest) GetAgentConfig() *SessionAgentConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *CreateSessionRequest) GetContextConfig() *SessionContextConfig {
	if x != nil {
		return x.ContextConfig
	}
	return nil
}

// CreateSessionResponse 创建会话响应
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_apiserver_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSessionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSessionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetSessionRequest 获取会话请求
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_apiserver_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetSessionResponse 获取会话响应
type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_apiserver_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

// ListSessionsRequest 获取会话列表请求
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_apiserver_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{7}
}

// ListSessionsResponse 获取会话列表响应
type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_apiserver_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpdateSessionRequest 更新会话请求
type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AgentConfig   *SessionAgentConfig    `protobuf:"bytes,4,opt,name=agent_config,json=agentConfig,proto3,oneof" json:"agent_config,omitempty"`
	ContextConfig *SessionContextConfig  `protobuf:"bytes,5,opt,name=context_config,json=contextConfig,proto3,oneof" json:"context_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_apiserver_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateSessionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateSessionRequest) GetAgentConfig() *SessionAgentConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *UpdateSessionRequest) GetContextConfig() *SessionContextConfig {
	if x != nil {
		return x.ContextConfig
	}
	return nil
}

// UpdateSessionResponse 更新会话响应
type UpdateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_apiserver_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSessionResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DeleteSessionRequest 删除会话请求
type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_apiserver_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSessionResponse 删除会话响应
type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_apiserver_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_apiserver_v1_session_proto protoreflect.FileDescriptor

const file_apiserver_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1aapiserver/v1/session.proto\x12\fapiserver.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf2\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12C\n" +
	"\fagent_config\x18\x05 \x01(\v2 .apiserver.v1.SessionAgentConfigR\vagentConfig\x12I\n" +
	"\x0econtext_config\x18\x06 \x01(\v2\".apiserver.v1.SessionContextConfigR\rcontextConfig\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe3\x01\n" +
	"\x12SessionAgentConfig\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12'\n" +
	"\x0fknowledge_bases\x18\x03 \x03(\tR\x0eknowledgeBases\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12%\n" +
	"\x0emax_iterations\x18\x05 \x01(\x05R\rmaxIterations\x12,\n" +
	"\x12web_search_enabled\x18\x06 \x01(\bR\x10webSearchEnabled\"\xac\x01\n" +
	"\x14SessionContextConfig\x12!\n" +
	"\fmax_messages\x18\x01 \x01(\x05R\vmaxMessages\x123\n" +
	"\x15compression_threshold\x18\x02 \x01(\x05R\x14compressionThreshold\x12<\n" +
	"\x1aenable_context_compression\x18\x03 \x01(\bR\x18enableContextCompression\"\xf9\x01\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12C\n" +
	"\fagent_config\x18\x04 \x01(\v2 .apiserver.v1.SessionAgentConfigR\vagentConfig\x12I\n" +
	"\x0econtext_config\x18\x05 \x01(\v2\".apiserver.v1.SessionContextConfigR\rcontextConfig\"x\n" +
	"\x15CreateSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12GetSessionResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.apiserver.v1.SessionR\asession\"\x15\n" +
	"\x13ListSessionsRequest\"_\n" +
	"\x14ListSessionsResponse\x121\n" +
	"\bsessions\x18\x01 \x03(\v2\x15.apiserver.v1.SessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc0\x02\n" +
	"\x14UpdateSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12H\n" +
	"\fagent_config\x18\x04 \x01(\v2 .apiserver.v1.SessionAgentConfigH\x02R\vagentConfig\x88\x01\x01\x12N\n" +
	"\x0econtext_config\x18\x05 \x01(\v2\".apiserver.v1.SessionContextConfigH\x03R\rcontextConfig\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_agent_configB\x11\n" +
	"\x0f_context_config\"x\n" +
	"\x15UpdateSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"&\n" +
	"\x14DeleteSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBAZ?github.com/ashwinyue/eino-show/pkg/api/apiserver/v1;apiserverv1b\x06proto3"

var (
	file_apiserver_v1_session_proto_rawDescOnce sync.Once
	file_apiserver_v1_session_proto_rawDescData []byte
)

func file_apiserver_v1_session_proto_rawDescGZIP() []byte {
	file_apiserver_v1_session_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_session_proto_rawDesc), len(file_apiserver_v1_session_proto_rawDesc)))
	})
	return file_apiserver_v1_session_proto_rawDescData
}

var file_apiserver_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_apiserver_v1_session_proto_goTypes = []any{
	(*Session)(nil),               // 0: apiserver.v1.Session
	(*SessionAgentConfig)(nil),    // 1: apiserver.v1.SessionAgentConfig
	(*SessionContextConfig)(nil),  // 2: apiserver.v1.SessionContextConfig
	(*CreateSessionRequest)(nil),  // 3: apiserver.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 4: apiserver.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),     // 5: apiserver.v1.GetSessionRequest
	(*GetSessionResponse)(nil),    // 6: apiserver.v1.GetSessionResponse
	(*ListSessionsRequest)(nil),   // 7: apiserver.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 8: apiserver.v1.ListSessionsResponse
	(*UpdateSessionRequest)(nil),  // 9: apiserver.v1.UpdateSessionRequest
	(*UpdateSessionResponse)(nil), // 10: apiserver.v1.UpdateSessionResponse
	(*DeleteSessionRequest)(nil),  // 11: apiserver.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 12: apiserver.v1.DeleteSessionResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_apiserver_v1_session_proto_depIdxs = []int32{
	1,  // 0: apiserver.v1.Session.agent_config:type_name -> apiserver.v1.SessionAgentConfig
	2,  // 1: apiserver.v1.Session.context_config:type_name -> apiserver.v1.SessionContextConfig
	13, // 2: apiserver.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: apiserver.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: apiserver.v1.CreateSessionRequest.agent_config:type_name -> apiserver.v1.SessionAgentConfig
	2,  // 5: apiserver.v1.CreateSessionRequest.context_config:type_name -> apiserver.v1.SessionContextConfig
	13, // 6: apiserver.v1.CreateSessionResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: apiserver.v1.GetSessionResponse.session:type_name -> apiserver.v1.Session
	0,  // 8: apiserver.v1.ListSessionsResponse.sessions:type_name -> apiserver.v1.Session
	1,  // 9: apiserver.v1.UpdateSessionRequest.agent_config:type_name -> apiserver.v1.SessionAgentConfig
	2,  // 10: apiserver.v1.UpdateSessionRequest.context_config:type_name -> apiserver.v1.SessionContextConfig
	13, // 11: apiserver.v1.UpdateSessionResponse.updated_at:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_apiserver_v1_session_proto_init() }
func file_apiserver_v1_session_proto_init() {
	if File_apiserver_v1_session_proto != nil {
		return
	}
	file_apiserver_v1_session_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_session_proto_rawDesc), len(file_apiserver_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_session_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_session_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_session_proto_msgTypes,
	}.Build()
	File_apiserver_v1_session_proto = out.File
	file_apiserver_v1_session_proto_goTypes = nil
	file_apiserver_v1_session_proto_depIdxs = nil
}
